package Assignment_2.src.gui;

import Assignment_2.src.command.CommandFactory;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Maarten de Klerk on 2-1-2017.
 */
public class CommandInput {
    private JPanel rootPanel;
    private JTextField commandTextField;
    private JButton executeButton;
    private GUIFacade guiFacade;

    public CommandInput() {

        guiFacade = GUIFacade.getInstance();


        executeButton.addActionListener(e -> {

            if (commandTextField.getText() != null) {
                CommandFactory commandFactory = new CommandFactory(commandTextField.getText());
                commandFactory.checkCommand();
            }
            commandTextField.setText("");
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Command");
        label1.setDisplayedMnemonic('C');
        label1.setDisplayedMnemonicIndex(0);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        rootPanel.add(label1, gbc);
        commandTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPanel.add(commandTextField, gbc);
        executeButton = new JButton();
        executeButton.setText("Execute");
        executeButton.setMnemonic('E');
        executeButton.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPanel.add(executeButton, gbc);
        label1.setLabelFor(commandTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}