package Assignment_2.src.gui;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Maarten de Klerk on 2-1-2017.
 */
public class CommandInput extends JFrame {
    private JPanel rootPanel;
    private JTextField commandTextField;
    private JLabel command;
    private JButton executeButton;

    private void createUIComponents() {

        setContentPane(rootPanel);
        pack();

        executeButton.addActionListener(e -> {
            //TODO perform action onclick
            if (commandTextField.getText() != null) {

            } else {

            }
        });

        setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        command = new JLabel();
        command.setEnabled(false);
        command.setText("Command");
        command.setToolTipText("Type a command to be executed");
        rootPanel.add(command);
        commandTextField = new JTextField();
        commandTextField.setColumns(20);
        commandTextField.setText("");
        rootPanel.add(commandTextField);
        executeButton = new JButton();
        executeButton.setHideActionText(false);
        executeButton.setText("Execute");
        executeButton.setToolTipText("Execute the command");
        rootPanel.add(executeButton);
        command.setLabelFor(commandTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
