package Assignment_2.src.gui;

import Assignment_2.src.command.CommandFactory;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Maarten de Klerk on 2-1-2017.
 */
public class CommandInput {
    private JPanel rootPanel;
    private JTextField commandTextField;
    private JLabel command;
    private JButton executeButton;

    public CommandInput() {

        executeButton.addActionListener(e -> {
            //TODO perform action onclick
            if (commandTextField.getText() != null) {
                CommandFactory commandFactory = new CommandFactory(commandTextField.getText());
//                commandFactory.checkCommand();

//                TEST: als de log werkt het onderstaande commenten
                if (commandFactory.checkCommand()){
                    commandTextField.setText("ging goed");

                } else {
                    commandTextField.setText("FOUT");

                }

//            Deze wordt (nog) niet gebruikt
//            } else {

            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        command = new JLabel();
        command.setEnabled(false);
        command.setText("Command");
        command.setToolTipText("Type a command to be executed");
        rootPanel.add(command);
        commandTextField = new JTextField();
        commandTextField.setColumns(20);
        commandTextField.setText("");
        rootPanel.add(commandTextField);
        executeButton = new JButton();
        executeButton.setHideActionText(false);
        executeButton.setText("Execute");
        executeButton.setToolTipText("Execute the command");
        rootPanel.add(executeButton);
        command.setLabelFor(commandTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
