package Assignment_2.src.gui;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 * Created by Maarten de Klerk on 2-1-2017.
 */
public class Logs implements View {

    private JPanel rootPanel;
    private JTextPane textPane;
    private GUIFacade guiFacade = GUIFacade.getInstance();

    public void update() {
        ArrayList<String> loglines = guiFacade.getLogLines();
        textPane.setText("");
        for (String l : loglines) {
            textPane.setText(textPane.getText() + l + "\n");
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, BorderLayout.CENTER);
        textPane = new JTextPane();
        textPane.setBackground(new Color(-14606047));
        textPane.setEditable(false);
        textPane.setForeground(new Color(-657931));
        scrollPane1.setViewportView(textPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
