package Assignment_2.src.gui;

import Assignment_2.src.models.Train;
import Assignment_2.src.models.WagonType;

import javax.swing.*;
import java.awt.*;
import java.util.*;

/**
 * Created by Maarten de Klerk on 2-1-2017.
 */
public class Output implements Observer {
    public JPanel rootPanel;
    private JTextPane textPane;
    private GUIFacade guiFacade = GUIFacade.getInstance();

    public void update(Observable o, Object arg) {
        textPane.setText("");

        ArrayList<Train> allTrains = guiFacade.getAllTrains();
        ArrayList<WagonType> allWagons = guiFacade.getAllWagons();

        textPane.setText(textPane.getText() + "All vehicles: \n\n");

        textPane.setText(textPane.getText() + "WAGONS: \n");

        if (allWagons != null || !allWagons.isEmpty()) {
            for (WagonType w : allWagons) {
                textPane.setText(textPane.getText() + "(" + w.getName() + ":" + w.getSeats() + ") \n");
            }
        } else {
            textPane.setText(textPane.getText() + "There are no Wagons. \n");
        }

        textPane.setText(textPane.getText() + "\n");
        textPane.setText(textPane.getText() + "TRAINS: \n");
        if (allTrains != null || !allTrains.isEmpty()) {

            for (Train t : allTrains) {
                textPane.setText(textPane.getText() + "(" + t.getName() + ")");
                for (WagonType w : t.getWagons()) {
                    textPane.setText(textPane.getText() + "(" + w.getName() + ":" + w.getSeats() + ")");
                }
                textPane.setText(textPane.getText() + "\n");
            }
        } else {
            textPane.setText(textPane.getText() + "There are no Trains. \n");
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMinimumSize(new Dimension(200, 180));
        rootPanel.setPreferredSize(new Dimension(500, 400));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, BorderLayout.CENTER);
        textPane = new JTextPane();
        textPane.setEditable(false);
        scrollPane1.setViewportView(textPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
